services:
  mysql:
    image: mysql:latest
    container_name: reservation-container
    restart: always
    environment:
      -  MYSQL_DATABASE=reservation
      -  MYSQL_PASSWORD=1234
      -  MYSQL_ROOT_PASSWORD=1234
      -  MYSQL_USER=son
    ports:
      - '3307:3306'
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
